export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_IS_LOADING = "FETCH_IS_LOADING";
export const FETCH_SHOWS_SUCCESS = "FETCH_SHOWS_SUCCESS";
export const FETCH_HAS_ERRORED = "FETCH_HAS_ERRORED";
