export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_IS_LOADING = "FETCH_IS_LOADING";
export const FETCH_SHOWS_SUCCESS = "FETCH_SHOWS_SUCCESS";
export const FETCH_HAS_ERRORED = "FETCH_HAS_ERRORED";
export const FETCH_ARTIST_DETAIL = "FETCH_ARTIST_DETAIL";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const IS_LOADING = "IS_LOADING";
