name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - name: Build site
        run: npm run build
        
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "react-redux-last-fm-app"
          entrypoint: https://deno.land/std@0.140.0/http/file_server.ts
          root: build
